productms.datasource.url: jdbc:h2:mem:productmsDb;DB_CLOSE_DELAY=-1
productms.datasource.username: sa
productms.datasource.password: 


config.server.url: http://192.168.99.100:8888

eureka.server.url: http://192.168.99.100:8761/eureka
            
